spring.application.name=ms-auth
spring.profiles.active=dev

springdoc.api-docs.path=/api/v1/auth/v3/api-docs
springdoc.swagger-ui.path=/api/v1/auth/doc/swagger-ui.html

springdoc.openapi.components.security-schemes.bearerAuth.type=http
springdoc.openapi.components.security-schemes.bearerAuth.scheme=bearer
springdoc.openapi.components.security-schemes.bearerAuth.bearerFormat=JWT
springdoc.openapi.security[0].bearerAuth=