spring:
  application:
    name: ms-auth
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /api/v1/auth/v3/api-docs
  swagger-ui:
    path: /api/v1/auth/doc/swagger-ui.html
  openapi:
    components:
      security-schemes:
        bearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - bearerAuth: []